# Generated by Django 4.2 on 2023-05-07 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_alter_vehicle_vehicle_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='options',
            field=models.CharField(choices=[('Super Admin', 'Super Admin'), ('Admin', 'Admin'), ('User', 'User')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only use alphanumeric characters')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('Two wheeler', 'Two wheeler'), ('Three wheeler', 'Three wheeler'), ('Four wheeler', 'Four wheeler')], max_length=100),
        ),
    ]
