# Generated by Django 4.2 on 2023-05-07 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_alter_users_options_alter_vehicle_vehicle_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='options',
            field=models.CharField(choices=[('SA', 'Super admin'), ('A', 'Admin'), ('U', 'user')], default='U', max_length=2),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only use alphanumeric characters')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('Two', 'Two wheeler'), ('Three', 'Three wheeler'), ('Four', 'Four wheeler')], max_length=5),
        ),
    ]
